#!/bin/sh
# AI評価文書を生成し、出典(モデル・日付・プロンプト)を再現可能に記録する。
# 出力は未修正の一次生成のまま保存する(de-AI編集や検出器での誘導をしない)。
# 使い方:
#   scripts/generate-ai-corpus.sh <id> <genre> <prompt-file> [model]
#   例: scripts/generate-ai-corpus.sh ai-tech-002 tech eval/prompts/ai-tech-002.txt claude-fable-5
set -eu

if [ $# -lt 3 ]; then
    echo "usage: $0 <id> <genre:tech|essay|business> <prompt-file> [model]" >&2
    exit 2
fi

ID="$1"
GENRE="$2"
PROMPT_FILE="$3"
MODEL="${4:-claude-fable-5}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/eval/corpus/${ID}.md"
PROMPT_STORE="${REPO_ROOT}/eval/prompts/${ID}.txt"

case "${GENRE}" in
    tech|essay|business) ;;
    *) echo "unknown genre: ${GENRE}" >&2; exit 2 ;;
esac
if [ ! -f "${PROMPT_FILE}" ]; then
    echo "prompt file not found: ${PROMPT_FILE}" >&2
    exit 1
fi
if [ -e "${OUT}" ]; then
    echo "refusing to overwrite existing document: ${OUT}" >&2
    exit 1
fi
if ! command -v claude >/dev/null 2>&1; then
    echo "claude CLI not found. プロンプトを手動でモデルへ渡し、出力を ${OUT} へ保存して" >&2
    echo "sha256とcorpus.toml断片は本スクリプトの末尾の形式に従って記録する。" >&2
    exit 1
fi

echo "==> generate: id=${ID} genre=${GENRE} model=${MODEL}" >&2
claude -p "$(cat "${PROMPT_FILE}")" --model "${MODEL}" > "${OUT}"

mkdir -p "${REPO_ROOT}/eval/prompts"
if [ ! -f "${PROMPT_STORE}" ]; then
    cp "${PROMPT_FILE}" "${PROMPT_STORE}"
fi

HASH="$(shasum -a 256 "${OUT}" | cut -d' ' -f1)"
CHARS="$(wc -m < "${OUT}" | tr -d ' ')"
TODAY="$(date +%Y-%m-%d)"

echo "==> saved: ${OUT} (${CHARS} chars)" >&2
echo "==> 注意: 語彙多様性ゲートはマスク後4,000字が必要。不足時は追記を依頼して再測定する。" >&2
echo "==> corpus.toml へ追加する断片:" >&2
cat <<EOF
[[document]]
id = "claude-${ID}"
path = "corpus/${ID}.md"
label = "ai"
genre = "${GENRE}"
source = "generated by Claude (${MODEL}) on ${TODAY} as an uncurated AI document; prompt recorded in eval/prompts/${ID}.txt"
license = "MIT"
sha256 = "${HASH}"
EOF
